// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EquityUIClient is the client API for EquityUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EquityUIClient interface {
	// ListEngineSpecs returns a list of Equity Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (EquityUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type equityUIClient struct {
	cc grpc.ClientConnInterface
}

func NewEquityUIClient(cc grpc.ClientConnInterface) EquityUIClient {
	return &equityUIClient{cc}
}

func (c *equityUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (EquityUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EquityUI_ServiceDesc.Streams[0], "/v1.EquityUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &equityUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EquityUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type equityUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *equityUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *equityUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.EquityUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EquityUIServer is the server API for EquityUI service.
// All implementations must embed UnimplementedEquityUIServer
// for forward compatibility
type EquityUIServer interface {
	// ListEngineSpecs returns a list of Equity Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, EquityUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedEquityUIServer()
}

// UnimplementedEquityUIServer must be embedded to have forward compatible implementations.
type UnimplementedEquityUIServer struct {
}

func (UnimplementedEquityUIServer) ListEngineSpecs(*ListEngineSpecsRequest, EquityUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedEquityUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedEquityUIServer) mustEmbedUnimplementedEquityUIServer() {}

// UnsafeEquityUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EquityUIServer will
// result in compilation errors.
type UnsafeEquityUIServer interface {
	mustEmbedUnimplementedEquityUIServer()
}

func RegisterEquityUIServer(s grpc.ServiceRegistrar, srv EquityUIServer) {
	s.RegisterService(&EquityUI_ServiceDesc, srv)
}

func _EquityUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EquityUIServer).ListEngineSpecs(m, &equityUIListEngineSpecsServer{stream})
}

type EquityUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type equityUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *equityUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EquityUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquityUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquityUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquityUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EquityUI_ServiceDesc is the grpc.ServiceDesc for EquityUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EquityUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.EquityUI",
	HandlerType: (*EquityUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _EquityUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _EquityUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "equity-ui.proto",
}
